data_dir = "data"

[sources.azure_eventhub_logs]
type = "azure_event_hub"
event_hub.fully_qualified_namespace = "crystal-cosmic.servicebus.windows.net"
event_hub.event_hub_names = ["eventhub-1"]
event_hub.consumer_group = "${'$'}Default"
event_hub.partition_count = 4

processing.batch_size = 100
processing.batch_timeout_ms = 1000
processing.worker_count = 4
processing.queue_size = 1000

checkpointing.enabled = true
checkpointing.storage_account_name = "chkpnt"
checkpointing.container_name = "chkpnt-container"
checkpointing.interval_seconds = 3
checkpointing.retry_max_attempts = 5
checkpointing.retry_initial_interval_ms = 1000

# Add a sink to see the events (for testing)
[sinks.console]
type = "console"
inputs = ["azure_eventhub_logs"]
encoding.codec = "json"
